[package]
name = "spade"
version = "2.0.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
edition = "2018"
autobenches = false

[dependencies]
doc-comment = "0.3"
smallvec = "1.4"
robust = "0.2.3"
num-traits = "0.2"
optional = "0.5.0"
rstar = { version = "0.9.0", optional = true }

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
default_features = false

[features]
serde = ["rstar/serde", "optional/serde", "serde_crate"]
rtree = []

[dev-dependencies]
approx = "0.5"
rand = "0.8.3"
rand_hc = "0.3"
cgmath = "0.18.0"
svg = "0.10.0"
criterion = { version = "0.3.4", features = ["html_reports"] }


[[bench]]
name = "benchmarks"
harness = false
required-features = ["rtree"]
debug = true
