[package]
name = "spade"
version = "2.0.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
edition = "2018"
autobenches = false

[lib]
bench = false

[dependencies]
smallvec = "1.4"
robust = "0.2.3"
num-traits = "0.2"
optional = "0.5.0"

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
features = ["derive"]

[features]
serde = ["optional/serde", "serde_crate"]

[dev-dependencies]
approx = "0.5"
rand = "0.8.3"
rand_hc = "0.3"
cgmath = "0.18.0"
svg = "0.10.0"
criterion = { version = "0.3.4", features = ["html_reports"] }


[[bench]]
name = "benchmarks"
harness = false
features = ["test"]